// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6IEUEP3YNvbe7yNVJIadOHtqpZGdu-io',
    appId: '1:50154965917:web:1cb1c3dddb9911f74bfd74',
    messagingSenderId: '50154965917',
    projectId: 'authorisation--1',
    authDomain: 'authorisation--1.firebaseapp.com',
    storageBucket: 'authorisation--1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IBojUP91FoK1PQ7C1Vs2ljCGOr0N5Dk',
    appId: '1:50154965917:android:93020fdfc7a3e41d4bfd74',
    messagingSenderId: '50154965917',
    projectId: 'authorisation--1',
    storageBucket: 'authorisation--1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSNaFV5OgBNGKBBACOhLwNqfO05fqw_h0',
    appId: '1:50154965917:ios:c6bcc23b81a4f1744bfd74',
    messagingSenderId: '50154965917',
    projectId: 'authorisation--1',
    storageBucket: 'authorisation--1.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSNaFV5OgBNGKBBACOhLwNqfO05fqw_h0',
    appId: '1:50154965917:ios:a5f87e6b886bf94d4bfd74',
    messagingSenderId: '50154965917',
    projectId: 'authorisation--1',
    storageBucket: 'authorisation--1.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
